# -*- coding: utf-8 -*-
"""akbank son hal

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B9RdjJuYrqFPke_8e_yf1QvWaxc-Oqj1
"""



class Library:
    def __init__(self, filename='books.txt'):
        self.filename = filename
        self.file = open(self.filename, 'a+')

    def __del__(self):
        self.file.close()

    def list_books(self):
        self.file.seek(0)
        books_data = self.file.read()
        books_list = books_data.splitlines()

        if not books_list:
            print("No books available.")
        else:
            for idx, book_info in enumerate(books_list, 1):
                book_data = book_info.split(',')
                print(f"Book {idx}: {book_data[0]} by {book_data[1]}")

    def add_book(self):
        title = input("Enter book title: ")
        author = input("Enter book author: ")
        release_year = input("Enter release year: ")
        num_pages = input("Enter number of pages: ")

        book_info = f"{title},{author},{release_year},{num_pages}\n"
        self.file.write(book_info)
        print(f"Book '{title}' is added successfully.")

    def remove_book(self):
        title_to_remove = input("Enter the title of the book to remove: ")

        self.file.seek(0)
        books_data = self.file.read()
        books_list = books_data.splitlines()

        found = False
        for book_info in books_list:
            if title_to_remove in book_info:
                found = True
                books_list.remove(book_info)
                break

        if found:
            self.file.seek(0)
            self.file.truncate()
            for book_info in books_list:
                self.file.write(book_info + '\n')
            print(f"Book '{title_to_remove}' is removed successfully.")
        else:
            print(f"Book '{title_to_remove}' not found.")

# Create an object named "lib" with "Library" class
lib = Library()

# Create a menu to interact with the "lib" object
while True:
    print("\n*** MENU ***")
    print("1) List Books")
    print("2) Add Book")
    print("3) Remove Book")
    print("4) Exit")

    choice = input("Enter your choice (1-4): ")

    if choice == '1':
        lib.list_books()
    elif choice == '2':
        lib.add_book()
    elif choice == '3':
        lib.remove_book()
    elif choice == '4':
        break
    else:
        print("Invalid choice. Please enter a number from 1 to 4.")